[package]
name = "rt-tls"
description = "Transport adapters (Direct, TLS, WebSocket, WSS, HTTP Upgrade)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rt-config = { workspace = true }
rt-websocket = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
