[package]
name = "rt-nftables"
description = "Isolated nftables table inet easy"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ipnet = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
rt-tun = { workspace = true }
